"use client";
import { useEffect, useMemo, useState } from "react";
import { runData } from "./run-data";

type View = "HOME" | "MARKET" | "STRATEGY ARENA" | "PORTFOLIO" | "SYSTEM";
const views: View[] = ["HOME", "MARKET", "STRATEGY ARENA", "PORTFOLIO", "SYSTEM"];
const money = (value: string) => `$${Number(value).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const Evidence = ({ children = "FACT" }: { children?: string }) => <span className={`evidence ${children.toLowerCase().replaceAll(" ", "-")}`}>{children}</span>;
const Metric = ({ label, value, note, unavailable = false }: { label: string; value: string; note: string; unavailable?: boolean }) => <article className="metric"><label>{label}</label><b className={unavailable ? "unavailable" : ""}>{value}</b><small>{note}</small><Evidence>{unavailable ? "INSUFFICIENT DATA" : "FACT"}</Evidence></article>;

export default function App() {
  const [view, setView] = useState<View>("HOME");
  const [eventIndex, setEventIndex] = useState(runData.events.length - 1);
  const [playing, setPlaying] = useState(false);
  const [speed, setSpeed] = useState("1×");
  const [decisionOpen, setDecisionOpen] = useState(false);
  const [advanced, setAdvanced] = useState(false);
  const event = runData.events[eventIndex];
  useEffect(() => { if (!playing) return; const delay = speed === "1×" ? 900 : speed === "10×" ? 250 : speed === "100×" ? 80 : 20; const timer = window.setInterval(() => setEventIndex(index => index >= runData.events.length - 1 ? (setPlaying(false), index) : index + 1), delay); return () => clearInterval(timer); }, [playing, speed]);
  const replayStatus = eventIndex === runData.events.length - 1 ? "COMPLETE" : playing ? "RUNNING" : "PAUSED";
  const page = useMemo(() => ({ HOME: <Home openDecision={() => setDecisionOpen(true)} />, MARKET: <Market eventIndex={eventIndex}/>, "STRATEGY ARENA": <Arena openDecision={() => setDecisionOpen(true)}/>, PORTFOLIO: <Portfolio/>, SYSTEM: <System replayStatus={replayStatus}/> }[view]), [view, eventIndex, replayStatus]);
  return <main className="shell"><aside className="rail"><div className="brand"><span className="brandMark">W</span><div><strong>WEALTH OS</strong><small>PRIVATE SYSTEM · 0.1</small></div></div><nav aria-label="Primary">{views.map((item,index)=><button onClick={()=>setView(item)} className={view===item?"navItem active":"navItem"} key={item}><span>0{index+1}</span>{item}</button>)}</nav><div className="railFoot"><i className="dot"/> SYSTEM NORMAL<br/><small>Deterministic replay</small></div></aside><section className="workspace"><header className="topbar"><div><span className="eyebrow">OBSERVE &amp; VALIDATE · {view}</span><h1>{view === "HOME" ? "System overview" : view.toLowerCase().replace(/\b\w/g, c => c.toUpperCase())}</h1></div><div className="runTag"><span>{replayStatus}</span><code>{runData.run.runId}</code></div></header><ReplayBar event={event} eventIndex={eventIndex} playing={playing} speed={speed} setPlaying={setPlaying} setSpeed={setSpeed} setEventIndex={setEventIndex}/>{page}</section>{decisionOpen&&<DecisionView advanced={advanced} setAdvanced={setAdvanced} close={()=>setDecisionOpen(false)}/>}</main>;
}

function ReplayBar({event,eventIndex,playing,speed,setPlaying,setSpeed,setEventIndex}: any){return <section className="replayStrip"><div><span className="eyebrow">LOGICAL REPLAY TIME</span><strong>{event.timestamp.replace("T"," · ").replace("+00:00"," UTC")}</strong></div><div className="miniTimeline"><i style={{width:`${((eventIndex+1)/runData.events.length)*100}%`}}/></div><div className="controls"><button onClick={()=>setEventIndex(Math.max(0,eventIndex-1))}>◀</button><button className="play" onClick={()=>setPlaying(!playing)}>{playing?"PAUSE":"PLAY"}</button><button onClick={()=>setEventIndex(Math.min(runData.events.length-1,eventIndex+1))}>STEP ▶</button>{["1×","10×","100×","MAX"].map(x=><button className={speed===x?"selected":""} onClick={()=>setSpeed(x)} key={x}>{x}</button>)}</div></section>}

function Home({openDecision}:{openDecision:()=>void}){return <><div className="notice"><i className="dot"/><strong>NO ACTION REQUIRED</strong><span>All monitored systems are within configured limits.</span><Evidence/></div><section className="metricGrid"><Metric label="NET ASSET VALUE" value={money(runData.portfolio.nav)} note="Ledger reconstructed"/><Metric label="NET P&L" value={`+${money(runData.metrics.netPnl)}`} note={`Gross ${money(runData.metrics.grossPnl)} − costs ${money(runData.metrics.costs)}`}/><Metric label="MAX DRAWDOWN" value="0.00005%" note="Observed peak-to-trough"/><Metric label="RISK STATE" value="GREEN / NORMAL" note="Configured limits clear"/></section><section className="mainGrid"><article className="panel health"><PanelTitle eyebrow="SYSTEM HEALTH" title="All layers operational" badge="GREEN / NORMAL"/>{["Data Health","Strategy Health","Execution Health","System Health"].map(x=><div className="healthRow" key={x}><span>{x}</span><strong><i className="dot"/>NORMAL</strong></div>)}</article><EquityPanel/><article className="panel activity"><PanelTitle eyebrow="LATEST DECISION" title="Momentum · AAPL" badge="PASS"/><p>{runData.decision.explanation}</p><dl><Row name="Intent" value="BUY 10"/><Row name="Executed" value="5 @ $105.021"/><Row name="Cost" value="$0.05"/></dl><button className="detailButton" onClick={openDecision}>OPEN DECISION TRACE →</button></article><MetricsPanel/></section></>}

function Market({eventIndex}:{eventIndex:number}){const event=runData.events[eventIndex];return <section className="viewGrid"><article className="panel marketHero"><PanelTitle eyebrow="CURRENT MARKET EVENT" title={`${event.symbol} · $${event.close.toFixed(2)}`} badge="FACT"/><PriceChart upto={eventIndex}/><div className="ohlc"><span>O <b>{event.open.toFixed(2)}</b></span><span>H <b>{event.high.toFixed(2)}</b></span><span>L <b>{event.low.toFixed(2)}</b></span><span>C <b>{event.close.toFixed(2)}</b></span><span>V <b>{event.volume.toLocaleString()}</b></span></div></article><article className="panel"><PanelTitle eyebrow="FEATURE SNAPSHOT" title="Point-in-time values" badge="FACT"/><div className="dataList">{Object.entries(runData.features).map(([key,value])=><Row key={key} name={key} value={value}/>)}</div></article><article className="panel span2"><PanelTitle eyebrow="RECENT EVENTS" title="Dataset replay" badge="FACT"/><table><thead><tr><th>Timestamp</th><th>Symbol</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume</th></tr></thead><tbody>{runData.events.slice(Math.max(0,eventIndex-5),eventIndex+1).reverse().map(e=><tr key={e.timestamp}><td>{e.timestamp.slice(11,19)}</td><td>{e.symbol}</td><td>{e.open}</td><td>{e.high}</td><td>{e.low}</td><td>{e.close}</td><td>{e.volume}</td></tr>)}</tbody></table></article></section>}

function Arena({openDecision}:{openDecision:()=>void}){return <><div className="honesty"><Evidence>UNCERTAINTY</Evidence><span>The fixture is too small for reliable comparative strategy performance. Missing statistics are not estimated.</span></div><section className="strategyGrid">{runData.strategies.map(s=><article className="panel strategyCard" key={s.id}><PanelTitle eyebrow={s.status} title={s.name} badge={s.trades?"ACTIVE":"NO SIGNAL"}/><div className="strategyStats"><Row name="Signals / intents" value={`${s.signals} / ${s.intents}`}/><Row name="Trades" value={String(s.trades)}/><Row name="Net P&L" value={s.netPnl?money(s.netPnl):"—"}/><Row name="Costs" value={s.costs?money(s.costs):"—"}/><Row name="Win rate" value="INSUFFICIENT DATA"/></div>{s.trades>0&&<button className="detailButton" onClick={openDecision}>VIEW DECISION →</button>}</article>)}</section></>}

function Portfolio(){return <section className="viewGrid"><article className="panel span2"><PanelTitle eyebrow="LEDGER RECONSTRUCTION" title="Portfolio state" badge="FACT"/><section className="metricGrid inner"><Metric label="CASH" value={money(runData.portfolio.cash)} note="After fills and fees"/><Metric label="NAV" value={money(runData.portfolio.nav)} note="Cash + marked positions"/><Metric label="REALIZED P&L" value="$0.00" note="No closed positions"/><Metric label="UNREALIZED P&L" value={`+${money(runData.portfolio.unrealizedPnl)}`} note="Current marks vs cost basis"/></section></article><article className="panel"><PanelTitle eyebrow="EXPOSURE" title="Risk footprint" badge="FACT"/><div className="dataList"><Row name="Gross exposure" value={money(runData.portfolio.grossExposure)}/><Row name="Net exposure" value={money(runData.portfolio.netExposure)}/><Row name="Current drawdown" value="0.00%"/><Row name="Risk state" value={runData.portfolio.riskState}/></div></article><article className="panel"><PanelTitle eyebrow="POSITIONS" title="Current holdings" badge="FACT"/>{runData.portfolio.positions.map(p=><div className="position" key={p.symbol}><strong>{p.symbol}</strong><span>{p.quantity} units</span><b>{money(p.value)}</b><small>Last {money(p.lastPrice)}</small></div>)}</article><EquityPanel/></section>}

function System({replayStatus}:{replayStatus:string}){return <section className="viewGrid"><article className="panel"><PanelTitle eyebrow="REPRODUCIBILITY" title="Run identity" badge="FACT"/><div className="dataList"><Row name="run_id" value={runData.run.runId}/><Row name="dataset_id" value={runData.run.datasetId}/><Row name="random_seed" value={String(runData.run.randomSeed)}/><Row name="ReplayClock" value={replayStatus}/><Row name="Events" value={String(runData.run.eventCount)}/><Row name="Ledger entries" value={String(runData.run.ledgerEntryCount)}/></div></article><article className="panel"><PanelTitle eyebrow="INTEGRITY" title="Hashes & code" badge="FACT"/><div className="hashBlock"><label>CONFIG HASH</label><code>{runData.run.configHash}</code><label>CODE COMMIT</label><code>{runData.run.codeCommit}</code></div></article><article className="panel span2"><PanelTitle eyebrow="CONFIG SNAPSHOT" title="Parameters used by this run" badge="FACT"/><div className="configGrid">{Object.entries(runData.config).map(([key,value])=><Row key={key} name={key} value={String(value)}/>)}</div></article></section>}

function DecisionView({advanced,setAdvanced,close}:any){const d=runData.decision;return <div className="modalBackdrop"><section className="decisionModal" role="dialog" aria-modal="true" aria-label="Decision trace"><header><div><span className="eyebrow">DECISION TRACE · {d.timestamp}</span><h1>{d.symbol} · {d.side}</h1></div><button onClick={close}>CLOSE ×</button></header><div className="modeToggle"><button className={!advanced?"selected":""} onClick={()=>setAdvanced(false)}>SIMPLE</button><button className={advanced?"selected":""} onClick={()=>setAdvanced(true)}>ADVANCED</button></div>{!advanced?<div className="simpleTrace"><TraceStep number="01" title="WHY?" body={d.explanation}/><TraceStep number="02" title="STRATEGY PROPOSED" body={`BUY ${d.desiredQty} units · signal score ${d.signalScore}`}/><TraceStep number="03" title="RISK ENGINE" body={`${d.riskDecision} · approved ${d.approvedQty} units`}/><TraceStep number="04" title="EXECUTION" body={`${d.execution} · ${d.fillQty} units at $${d.fillPrice}`}/><TraceStep number="05" title="RESULT" body={`Fee $${d.fee}. Transaction contribution ${d.pnl}. Position changed only after Fill.`}/></div>:<div className="advancedTrace"><TraceSection title="FEATURES">{Object.entries(runData.features).map(([k,v])=><Row key={k} name={k} value={v}/>)}</TraceSection><TraceSection title="TRADE INTENT"><Row name="reason_codes" value={d.reasonCodes.join(", ")}/><Row name="expected_alpha" value={d.expectedAlpha}/><Row name="desired_qty" value={d.desiredQty}/><Row name="portfolio_requested_qty" value={d.requestedQty}/></TraceSection><TraceSection title="RISK / ORDER"><Row name="decision" value={d.riskDecision}/><Row name="approved_qty" value={d.approvedQty}/><Row name="order_id" value={d.orderId}/><Row name="status" value={d.orderStatus}/></TraceSection><TraceSection title="EXECUTION / FILL"><Row name="bid / ask" value={`${d.bid} / ${d.ask}`}/><Row name="slippage / latency" value={`${d.slippageBps} bps / ${d.latencyMs} ms`}/><Row name="fill_id" value={d.fillId}/><Row name="qty / price / fee" value={`${d.fillQty} / ${d.fillPrice} / ${d.fee}`}/></TraceSection><TraceSection title="RAW AUDIT TRACE"><pre>{d.ledger.join("\n↓\n")}</pre></TraceSection></div>}</section></div>}

function MetricsPanel(){const m=runData.metrics;return <article className="panel metricsPanel"><PanelTitle eyebrow="RUN METRICS" title="Performance & evidence" badge="LEDGER BASED"/><div className="metricsRows"><Row name="Gross P&L" value={money(m.grossPnl)}/><Row name="Execution costs" value={money(m.costs)}/><Row name="Net P&L" value={money(m.netPnl)}/><Row name="Total return" value="0.274505%"/><Row name="Turnover" value="6.045684%"/><Row name="Trade count" value={String(m.tradeCount)}/>{["CAGR","Sharpe","Sortino","Calmar","Profit factor","Expectancy","Win rate"].map(x=><Row key={x} name={x} value="INSUFFICIENT DATA"/>)}</div></article>}
function EquityPanel(){return <article className="panel equityPanel"><PanelTitle eyebrow="EQUITY CURVE" title="NAV history" badge="FACT"/><div className="equityChart"><div className="equityLine"/><span className="startLabel">$100,000</span><span className="endLabel">$100,274.51</span></div><p>Maximum observed drawdown: <strong>0.00005%</strong></p></article>}
function PriceChart({upto}:{upto:number}){return <div className="priceChart">{runData.events.slice(0,upto+1).map((e,i)=><i key={e.timestamp} style={{height:`${20+(e.close-100)*4}px`}} title={`${e.timestamp}: ${e.close}`}/>)}</div>}
function PanelTitle({eyebrow,title,badge}:{eyebrow:string,title:string,badge:string}){return <div className="panelHead"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><span className="normalPill">{badge}</span></div>}
function Row({name,value}:{name:string,value:string}){return <div className="dataRow"><span>{name}</span><strong>{value}</strong></div>}
function TraceStep({number,title,body}:{number:string,title:string,body:string}){return <article><span>{number}</span><div><label>{title}</label><p>{body}</p></div></article>}
function TraceSection({title,children}:{title:string,children:React.ReactNode}){return <section><h3>{title}</h3>{children}</section>}
