/* eslint-disable @typescript-eslint/no-explicit-any, jsx-a11y/label-has-associated-control */
"use client";
import { useEffect, useMemo, useState } from "react";
import observation from "./run-data.json";

type View="HOME"|"MARKET"|"STRATEGY ARENA"|"PORTFOLIO"|"SYSTEM";
type Snapshot=(typeof observation.snapshots)[number];
const views:View[]=["HOME","MARKET","STRATEGY ARENA","PORTFOLIO","SYSTEM"];
const money=(v:unknown)=>v==null?"NOT AVAILABLE":`$${Number(v).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const percent=(v:unknown)=>v==null?"INSUFFICIENT DATA":`${(Number(v)*100).toFixed(5)}%`;
const label=(v:string)=>v.replaceAll("_"," ").toUpperCase();

export default function App(){
 const[view,setView]=useState<View>("HOME"),[index,setIndex]=useState(observation.snapshots.length-1),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState("1x"),[decisionOpen,setDecisionOpen]=useState(false),[advanced,setAdvanced]=useState(false);
 const snap=observation.snapshots[index] as Snapshot;
 useEffect(()=>{if(!playing)return;const ms=speed==="1x"?900:speed==="10x"?250:speed==="100x"?80:20,timer=setInterval(()=>setIndex(i=>i>=observation.snapshots.length-1?(setPlaying(false),i):i+1),ms);return()=>clearInterval(timer)},[playing,speed]);
 const status=index===observation.snapshots.length-1?"COMPLETE":playing?"RUNNING":"PAUSED";
 const content=useMemo(()=>({HOME:<Home snap={snap} open={()=>setDecisionOpen(true)}/>,MARKET:<Market snap={snap} index={index}/>,"STRATEGY ARENA":<Arena snap={snap} open={()=>setDecisionOpen(true)}/>,PORTFOLIO:<Portfolio snap={snap}/>,SYSTEM:<System snap={snap} status={status}/>}[view]),[view,snap,index,status]);
 return <main className="shell"><aside className="rail"><div className="brand"><span className="brandMark">W</span><div><strong>WEALTH OS</strong><small>PRIVATE SYSTEM · 0.1</small></div></div><nav aria-label="Primary">{views.map((v,i)=><button key={v} onClick={()=>setView(v)} className={view===v?"navItem active":"navItem"}><span>0{i+1}</span>{v}</button>)}</nav><div className="railFoot"><i className="dot"/> SYSTEM NORMAL<br/><small>Deterministic replay</small></div></aside><section className="workspace"><header className="topbar"><div><span className="eyebrow">OBSERVE &amp; VALIDATE · {view}</span><h1>{view==="HOME"?"System overview":view}</h1></div><div className="runTag"><span>{status}</span><code>{snap.run.run_id}</code></div></header><ReplayBar snap={snap} index={index} setIndex={setIndex} playing={playing} setPlaying={setPlaying} speed={speed} setSpeed={setSpeed}/>{content}</section>{decisionOpen&&<Decision snap={snap} advanced={advanced} setAdvanced={setAdvanced} close={()=>setDecisionOpen(false)}/>}</main>
}
function ReplayBar({snap,index,setIndex,playing,setPlaying,speed,setSpeed}:any){return <section className="replayStrip"><div><span className="eyebrow">LOGICAL REPLAY TIME</span><strong>{snap.replay.timestamp.replace("T"," · ")}</strong></div><div className="miniTimeline"><i style={{width:`${((index+1)/observation.snapshots.length)*100}%`}}/></div><div className="controls"><button aria-label="Previous event" onClick={()=>{setPlaying(false);setIndex(Math.max(0,index-1))}}>◀</button><button className="play" onClick={()=>setPlaying(!playing)}>{playing?"PAUSE":"PLAY"}</button><button onClick={()=>{setPlaying(false);setIndex(Math.min(observation.snapshots.length-1,index+1))}}>STEP ▶</button>{["1x","10x","100x","MAX"].map((x)=><button key={x} className={speed===x?"selected":""} onClick={()=>setSpeed(x)}>{x.replace("x","×")}</button>)}</div></section>}
function Home({snap,open}:{snap:Snapshot,open:()=>void}){const d=snap.decisions.at(-1);return <><div className="notice"><i className="dot"/><strong>NO ACTION REQUIRED</strong><span>All monitored systems are within configured limits.</span><Evidence/></div><section className="metricGrid"><Metric name="NET ASSET VALUE" value={money(snap.portfolio.nav)} note="Ledger reconstructed"/><Metric name="NET P&L" value={money(snap.metrics.net_pnl.value)} note={`Gross ${money(snap.metrics.gross_pnl.value)} − costs ${money(snap.metrics.execution_costs.value)}`}/><Metric name="MAX DRAWDOWN" value={percent(snap.metrics.maximum_drawdown.value)} note="Observed peak-to-trough"/><Metric name="RISK STATE" value="GREEN / NORMAL" note="Configured limits clear"/></section><section className="mainGrid"><article className="panel health"><Title eyebrow="SYSTEM HEALTH" title="All layers operational" badge="FACT"/>{snap.health.map(h=><Row key={h.label} name={h.label} value={h.status}/>)}</article><Equity snap={snap}/><article className="panel activity"><Title eyebrow="LATEST DECISION" title={d?`${d.advanced.intent.strategy_id} · ${d.advanced.intent.symbol}`:"No completed trade yet"} badge={d?d.advanced.risk_assessment.decision.toUpperCase():"NOT AVAILABLE"}/><p>{d?.simple.why??"Replay has not reached a completed fill."}</p>{d&&<button className="detailButton" onClick={open}>OPEN DECISION TRACE →</button>}</article><Metrics snap={snap}/></section></>}
function Market({snap,index}:{snap:Snapshot,index:number}){const e=snap.market.event,data=e.data,events=observation.snapshots.slice(0,index+1).map(s=>s.market.event).filter(x=>x.data.symbol===data.symbol);return <section className="viewGrid"><article className="panel marketHero"><Title eyebrow="CURRENT MARKET EVENT" title={`${data.symbol} · ${money(data.close)}`} badge="FACT"/><PriceChart events={events}/><div className="ohlc"><span>O <b>{data.open}</b></span><span>H <b>{data.high}</b></span><span>L <b>{data.low}</b></span><span>C <b>{data.close}</b></span><span>V <b>{data.volume}</b></span></div></article><article className="panel"><Title eyebrow="FEATURE SNAPSHOT" title="Point-in-time values" badge={snap.market.features?"FACT":"NOT AVAILABLE"}/><div className="dataList">{snap.market.features?Object.entries(snap.market.features).filter(([k])=>!["timestamp","symbol"].includes(k)).map(([k,v])=><Row key={k} name={k} value={v??"NOT AVAILABLE"}/>):<p>Missing data is explicit at this replay point.</p>}</div></article><article className="panel span2"><Title eyebrow="RECENT EVENTS" title="Dataset replay" badge="FACT"/><table><thead><tr><th>Timestamp</th><th>Symbol</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume</th></tr></thead><tbody>{[...snap.market.recent_events].reverse().map(e=><tr key={e.event_id}><td>{e.timestamp.slice(11,19)}</td><td>{e.data.symbol}</td><td>{e.data.open}</td><td>{e.data.high}</td><td>{e.data.low}</td><td>{e.data.close}</td><td>{e.data.volume}</td></tr>)}</tbody></table></article></section>}
function Arena({snap,open}:{snap:Snapshot,open:()=>void}){return <><div className="honesty"><Evidence value="UNCERTAINTY"/><span>The fixture is too small for reliable comparative performance. Missing statistics are not estimated.</span></div><section className="strategyGrid">{snap.strategies.map(s=><article className="panel strategyCard" key={s.strategy_id}><Title eyebrow={s.status} title={label(s.strategy_id)} badge={s.trades?"ACTIVE":"NO SIGNAL"}/><Row name="Signals / intents" value={`${s.signals} / ${s.intents}`}/><Row name="Trades" value={s.trades}/><Row name="Net P&L" value={s.net_pnl==null?"INSUFFICIENT DATA":money(s.net_pnl)}/><Row name="Costs" value={s.costs==null?"NOT AVAILABLE":money(s.costs)}/><Row name="Win rate" value="INSUFFICIENT DATA"/>{s.trades>0&&<button className="detailButton" onClick={open}>VIEW DECISION →</button>}</article>)}</section></>}
function Portfolio({snap}:{snap:Snapshot}){const p=snap.portfolio;return <section className="viewGrid"><article className="panel span2"><Title eyebrow="LEDGER RECONSTRUCTION" title="Portfolio state" badge="FACT"/><section className="metricGrid inner"><Metric name="CASH" value={money(p.cash)} note="After visible fills and fees"/><Metric name="NAV" value={money(p.nav)} note="Cash + current marked positions"/><Metric name="REALIZED P&L" value={money(p.realized_pnl)} note="Closed positions"/><Metric name="UNREALIZED P&L" value={money(p.unrealized_pnl)} note="Current marks vs cost basis"/></section></article><article className="panel"><Title eyebrow="EXPOSURE" title="Risk footprint" badge="FACT"/><Row name="Gross exposure" value={money(p.gross_exposure)}/><Row name="Net exposure" value={money(p.net_exposure)}/><Row name="Current drawdown" value={percent(p.drawdown)}/></article><article className="panel"><Title eyebrow="POSITIONS" title="Current holdings" badge={Object.keys(p.positions).length?"FACT":"NOT AVAILABLE"}/>{Object.keys(p.positions).length?Object.entries(p.positions).map(([symbol,qty])=><div className="position" key={symbol}><strong>{symbol}</strong><span>{qty} units</span><b>{money(Number(qty)*Number(p.last_prices[symbol as keyof typeof p.last_prices]))}</b><small>Last {money(p.last_prices[symbol as keyof typeof p.last_prices])}</small></div>):<p>No position at this replay point.</p>}</article><article className="panel span2"><Title eyebrow="LEDGER" title={`${snap.ledger.length} visible records`} badge="APPEND ONLY"/><div className="dataList">{snap.ledger.slice(-10).map(e=><Row key={e.entry_id} name={`${e.sequence} · ${e.entry_type}`} value={e.description||e.amount}/>)}</div></article><Equity snap={snap}/></section>}
function System({snap,status}:{snap:Snapshot,status:string}){return <section className="viewGrid"><article className="panel"><Title eyebrow="REPRODUCIBILITY" title="Run identity" badge="FACT"/><Row name="run_id" value={snap.run.run_id}/><Row name="dataset_id" value={snap.run.dataset_id}/><Row name="random_seed" value={snap.run.random_seed}/><Row name="ReplayClock" value={status}/><Row name="event index / count" value={`${snap.replay.event_index+1} / ${snap.replay.event_count}`}/><Row name="ledger count" value={snap.run.ledger_entry_count}/></article><article className="panel"><Title eyebrow="INTEGRITY" title="Hashes & code" badge="FACT"/><div className="hashBlock"><label>CONFIG HASH</label><code>{snap.run.config_hash}</code><label>RESULT HASH</label><code>{snap.run.result_hash}</code><label>CODE COMMIT</label><code>{snap.run.code_commit}</code></div></article><article className="panel span2"><Title eyebrow="CONFIG SNAPSHOT" title="Parameters used by this run" badge="FACT"/><div className="configGrid">{Object.entries(snap.config_snapshot).map(([k,v])=><Row key={k} name={k} value={String(v)}/>)}</div></article></section>}
function Decision({snap,advanced,setAdvanced,close}:any){const d=snap.decisions.at(-1);if(!d)return <div className="modalBackdrop"><section className="decisionModal"><header><h1>No completed decision at this replay point</h1><button onClick={close}>CLOSE ×</button></header><p>Advance replay until a Fill and its ledger records exist.</p></section></div>;const a=d.advanced;return <div className="modalBackdrop"><section className="decisionModal" role="dialog" aria-modal="true"><header><div><span className="eyebrow">DECISION TRACE · {a.intent.timestamp}</span><h1>{a.intent.symbol} · {a.intent.side.toUpperCase()}</h1></div><button onClick={close}>CLOSE ×</button></header><div className="modeToggle"><button className={!advanced?"selected":""} onClick={()=>setAdvanced(false)}>SIMPLE</button><button className={advanced?"selected":""} onClick={()=>setAdvanced(true)}>ADVANCED</button></div>{!advanced?<div className="simpleTrace">{Object.entries(d.simple).map(([k,v],i)=><Trace key={k} n={String(i+1).padStart(2,"0")} title={label(k)} body={v}/>)}</div>:<div className="advancedTrace"><TraceSection title="MARKET EVENT"><Row name="timestamp" value={a.market_event.timestamp}/><Row name="OHLCV" value={`${a.market_event.data.open} / ${a.market_event.data.high} / ${a.market_event.data.low} / ${a.market_event.data.close} / ${a.market_event.data.volume}`}/></TraceSection><TraceSection title="FEATURES">{Object.entries(a.features).map(([k,v])=><Row key={k} name={k} value={v??"NOT AVAILABLE"}/>)}</TraceSection><TraceSection title="INTENT / RISK"><Row name="signal score" value={a.intent.signal_score}/><Row name="reason codes" value={a.intent.reason_codes.join(", ")}/><Row name="requested / approved" value={`${a.portfolio_request.requested_qty} / ${a.risk_assessment.approved_qty}`}/><Row name="risk decision" value={a.risk_assessment.decision}/></TraceSection><TraceSection title="ORDER / EXECUTION / FILL"><Row name="order" value={`${a.order.order_type} · ${a.order.status}`}/><Row name="execution" value={`${a.execution.outcome} · ${a.execution.reason}`}/><Row name="fill" value={`${a.fill.qty} @ ${a.fill.price}`}/><Row name="fee" value={a.fill.fee}/></TraceSection><TraceSection title="LEDGER / P&L"><Row name="transaction P&L" value={a.pnl}/><pre>{a.ledger_entries.map((e:any)=>`${e.sequence} · ${e.entry_type} · ${e.amount}`).join("\n")}</pre></TraceSection></div>}</section></div>}
function Metrics({snap}:{snap:Snapshot}){return <article className="panel metricsPanel"><Title eyebrow="RUN METRICS" title="Performance & evidence" badge="LEDGER BASED"/><div className="metricsRows">{Object.entries(snap.metrics).map(([k,m])=><Row key={k} name={k} value={m.value==null?label(m.status):k.includes("return")||k.includes("drawdown")||k==="turnover"?percent(m.value):String(m.value)}/>)}</div></article>}
function Equity({snap}:{snap:Snapshot}){const c=snap.equity_curve;return <article className="panel equityPanel"><Title eyebrow="EQUITY CURVE" title="NAV history" badge="FACT"/><div className="equityChart"><div className="equityLine"/><span className="startLabel">{money(c[0]?.nav)}</span><span className="endLabel">{money(c.at(-1)?.nav)}</span></div><p>Maximum observed drawdown: <strong>{percent(snap.metrics.maximum_drawdown.value)}</strong></p></article>}
function PriceChart({events}:{events:any[]}){return <div className="priceChart">{events.map(e=><i key={e.event_id} style={{height:`${Math.max(4,20+(Number(e.data.close)-Number(events[0].data.close))*6)}px`}} title={`${e.timestamp}: ${e.data.close}`}/>)}</div>}
function Evidence({value="FACT"}:{value?:string}){return <em className={`evidence ${value.toLowerCase().replaceAll(" ","-")}`}>{value}</em>}
function Metric({name,value,note}:{name:string,value:string,note:string}){return <article className="metric"><label>{name}</label><b>{value}</b><small>{note}</small><Evidence value={value.includes("DATA")||value.includes("AVAILABLE")?value:"FACT"}/></article>}
function Title({eyebrow,title,badge}:{eyebrow:string,title:string,badge:string}){return <div className="panelHead"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><span className="normalPill">{badge}</span></div>}
function Row({name,value}:{name:string,value:unknown}){return <div className="dataRow"><span>{label(name)}</span><strong>{String(value)}</strong></div>}
function Trace({n,title,body}:{n:string,title:string,body:unknown}){return <article><span>{n}</span><div><label>{title}</label><p>{String(body)}</p></div></article>}
function TraceSection({title,children}:{title:string,children:React.ReactNode}){return <section><h3>{title}</h3>{children}</section>}
