/* eslint-disable @typescript-eslint/no-explicit-any, jsx-a11y/label-has-associated-control */
"use client";
import { useEffect, useMemo, useState } from "react";
import observation from "./run-data.json";

type View="HOME"|"MARKET"|"STRATEGY ARENA"|"PORTFOLIO"|"SYSTEM";
type Snapshot=(typeof observation.snapshots)[number];
const views:View[]=["HOME","MARKET","STRATEGY ARENA","PORTFOLIO","SYSTEM"];
const money=(v:unknown)=>v==null?"NOT AVAILABLE":`$${Number(v).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const percent=(v:unknown)=>v==null?"INSUFFICIENT DATA":`${(Number(v)*100).toFixed(5)}%`;
const label=(v:string)=>v.replaceAll("_"," ").toUpperCase();

export default function App(){
 const[view,setView]=useState<View>("HOME"),[index,setIndex]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState("1x"),[decisionOpen,setDecisionOpen]=useState(false),[advanced,setAdvanced]=useState(false),[pauseOnFill,setPauseOnFill]=useState(false);
 const snap=observation.snapshots[index] as Snapshot;
 useEffect(()=>{if(!playing)return;const ms=speed==="1x"?1200:speed==="10x"?400:speed==="100x"?120:25,timer=setInterval(()=>setIndex(i=>{const next=Math.min(observation.snapshots.length-1,i+1),hasFill=pauseOnFill&&observation.snapshots[next].ledger.some(e=>e.entry_type==="fill")&&!observation.snapshots[i].ledger.some(e=>e.entry_type==="fill");if(next===observation.snapshots.length-1||hasFill)setPlaying(false);return next}),ms);return()=>clearInterval(timer)},[playing,speed,pauseOnFill]);
 const status=index===observation.snapshots.length-1?"COMPLETE":playing?"RUNNING":"PAUSED";
 const content=useMemo(()=>({HOME:<Home snap={snap} open={()=>setDecisionOpen(true)}/>,MARKET:<Market snap={snap} index={index}/>,"STRATEGY ARENA":<Arena snap={snap} open={()=>setDecisionOpen(true)}/>,PORTFOLIO:<Portfolio snap={snap}/>,SYSTEM:<System snap={snap} status={status}/>}[view]),[view,snap,index,status]);
 return <main className="shell"><aside className="rail"><div className="brand"><span className="brandMark">W</span><div><strong>WEALTH OS</strong><small>RESEARCH SYSTEM · 0.2-A</small></div></div><nav aria-label="Primary">{views.map((v,i)=><button key={v} onClick={()=>setView(v)} className={view===v?"navItem active":"navItem"}><span>0{i+1}</span>{v}</button>)}</nav><div className="railFoot"><i className="dot"/> HISTORICAL REPLAY<br/><small>Simulated execution</small></div></aside><section className="workspace"><ResearchHeader snap={snap}/><header className="topbar"><div><span className="eyebrow">RESEARCH / HISTORICAL REPLAY · {view}</span><h1>{view==="HOME"?"Dynamic research runtime":view}</h1></div><div className={`runTag ${status.toLowerCase()}`}><span>{status==="RUNNING"?"●":status==="PAUSED"?"Ⅱ":"■"} {status}</span><code>{snap.run.run_id}</code></div></header><ReplayBar snap={snap} index={index} setIndex={setIndex} playing={playing} setPlaying={setPlaying} speed={speed} setSpeed={setSpeed} reset={()=>{setPlaying(false);setIndex(0);setDecisionOpen(false)}} pauseOnFill={pauseOnFill} setPauseOnFill={setPauseOnFill}/>{content}<EventStream snap={snap}/></section>{decisionOpen&&<Decision snap={snap} advanced={advanced} setAdvanced={setAdvanced} close={()=>setDecisionOpen(false)}/>}</main>
}
function ResearchHeader({snap}:{snap:Snapshot}){return <section className="researchHeader"><strong>RESEARCH RUN</strong><span className="realBadge">REAL HISTORICAL MARKET DATA</span><span>Source <b>{snap.run.dataset_source}</b></span><span>Period <b>{observation.dataset.start.slice(0,10)} → {observation.dataset.end.slice(0,10)}</b></span><span>Symbols <b>{observation.dataset.symbols.join(" · ")}</b></span><span>Frequency <b>{snap.run.dataset_frequency}</b></span><span>Seed <b>{snap.run.random_seed}</b></span></section>}
function ReplayBar({snap,index,setIndex,playing,setPlaying,speed,setSpeed,reset,pauseOnFill,setPauseOnFill}:any){return <section className="replayStrip"><div><span className="eyebrow">REPLAY TIME · AMERICA/NEW_YORK</span><strong>{snap.replay.timestamp.replace("T"," · ")}</strong><small>EVENT {index+1} / {observation.snapshots.length} · {speed.replace("x","×")}</small></div><div className="miniTimeline"><i style={{width:`${((index+1)/observation.snapshots.length)*100}%`}}/></div><div className="controls"><button aria-label="Previous event" onClick={()=>{setPlaying(false);setIndex(Math.max(0,index-1))}}>◀</button><button className="play" onClick={()=>setPlaying(!playing)}>{playing?"PAUSE":"PLAY"}</button><button onClick={()=>{setPlaying(false);setIndex(Math.min(observation.snapshots.length-1,index+1))}}>STEP ▶</button><button aria-label="Next event" onClick={()=>setIndex(Math.min(observation.snapshots.length-1,index+1))}>NEXT ▶</button>{["1x","10x","100x","MAX"].map((x)=><button key={x} className={speed===x?"selected":""} onClick={()=>setSpeed(x)}>{x.replace("x","×")}</button>)}<button onClick={reset}>RESET RUN</button><label className="autoPause"><input type="checkbox" checked={pauseOnFill} onChange={e=>setPauseOnFill(e.target.checked)}/> AUTO PAUSE: FILL</label></div></section>}
function Home({snap,open}:{snap:Snapshot,open:()=>void}){const d=snap.decisions.at(-1),e=snap.market.event.data;return <><div className="notice"><i className="dot"/><strong>{snap.replay.event_index+1===snap.replay.event_count?"RUN COMPLETE":"SYSTEM OBSERVING"}</strong><span>{e.symbol} {money(e.close)} · state projected at current replay cursor.</span><Evidence/></div><section className="metricGrid"><Metric name="NET ASSET VALUE" value={money(snap.portfolio.nav)} note="Ledger reconstructed"/><Metric name="NET P&L" value={money(snap.metrics.net_pnl.value)} note={`Gross ${money(snap.metrics.gross_pnl.value)} − costs ${money(snap.metrics.execution_costs.value)}`}/><Metric name="MAX DRAWDOWN" value={percent(snap.metrics.maximum_drawdown.value)} note="No future NAV"/><Metric name="RISK STATE" value="GREEN / NORMAL" note="Configured limits clear"/></section><Pipeline snap={snap}/><section className="mainGrid"><Equity snap={snap}/><article className="panel"><Title eyebrow="MARKET" title={`${e.symbol} · ${money(e.close)}`} badge="MOVING"/><Row name="current bar" value={`${e.open} / ${e.high} / ${e.low} / ${e.close}`}/><Row name="volume" value={e.volume}/></article><article className="panel activity"><Title eyebrow="LATEST DECISION" title={d?`${d.advanced.intent.strategy_id} · ${d.advanced.intent.symbol}`:"No completed trade yet"} badge={d?d.advanced.risk_assessment.decision.toUpperCase():"OBSERVING"}/><p>{d?.simple.why??"Replay has not reached a completed fill."}</p>{d&&<button className="detailButton" onClick={open}>WHY? OPEN DECISION TRACE →</button>}</article><Metrics snap={snap}/></section></>}
function Market({snap,index}:{snap:Snapshot,index:number}){const e=snap.market.event,data=e.data,events=observation.snapshots.slice(0,index+1).map(s=>s.market.event).filter(x=>x.data.symbol===data.symbol),change=events.length>1?(Number(data.close)/Number(events.at(-2)!.data.close)-1)*100:0;return <section className="viewGrid"><article className="panel marketHero"><Title eyebrow="CURRENT MARKET EVENT" title={`${data.symbol} · ${money(data.close)} · ${change>=0?"+":""}${change.toFixed(2)}%`} badge="REAL DATA"/><PriceChart events={events}/><div className="ohlc"><span>O <b>{data.open}</b></span><span>H <b>{data.high}</b></span><span>L <b>{data.low}</b></span><span>C <b>{data.close}</b></span><span>V <b>{data.volume}</b></span></div></article><article className="panel"><Title eyebrow="FEATURE SNAPSHOT" title="Point-in-time values" badge={snap.market.features?"UPDATED":"NOT AVAILABLE"}/><div className="dataList">{snap.market.features?Object.entries(snap.market.features).filter(([k])=>!["timestamp","symbol"].includes(k)).map(([k,v])=><Row key={k} name={k} value={v??"NOT AVAILABLE"}/>):<p>Missing data is explicit at this replay point.</p>}</div></article><article className="panel span2"><Title eyebrow="RECENT EVENTS" title="Visible market history only" badge="NO FUTURE DATA"/><table><thead><tr><th>Timestamp</th><th>Symbol</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume</th></tr></thead><tbody>{[...snap.market.recent_events].reverse().map(e=><tr key={e.event_id}><td>{e.timestamp.slice(0,16).replace("T"," ")}</td><td>{e.data.symbol}</td><td>{e.data.open}</td><td>{e.data.high}</td><td>{e.data.low}</td><td>{e.data.close}</td><td>{e.data.volume}</td></tr>)}</tbody></table></article></section>}
function Arena({snap,open}:{snap:Snapshot,open:()=>void}){return <><div className="honesty"><Evidence value="UNCERTAINTY"/><span>The fixture is too small for reliable comparative performance. Missing statistics are not estimated.</span></div><section className="strategyGrid">{snap.strategies.map(s=><article className="panel strategyCard" key={s.strategy_id}><Title eyebrow={s.status} title={label(s.strategy_id)} badge={s.trades?"ACTIVE":"NO SIGNAL"}/><Row name="Signals / intents" value={`${s.signals} / ${s.intents}`}/><Row name="Trades" value={s.trades}/><Row name="Net P&L" value={s.net_pnl==null?"INSUFFICIENT DATA":money(s.net_pnl)}/><Row name="Costs" value={s.costs==null?"NOT AVAILABLE":money(s.costs)}/><Row name="Win rate" value="INSUFFICIENT DATA"/>{s.trades>0&&<button className="detailButton" onClick={open}>VIEW DECISION →</button>}</article>)}</section></>}
function Portfolio({snap}:{snap:Snapshot}){const p=snap.portfolio;return <section className="viewGrid"><article className="panel span2"><Title eyebrow="LEDGER RECONSTRUCTION" title="Portfolio state" badge="FACT"/><section className="metricGrid inner"><Metric name="CASH" value={money(p.cash)} note="After visible fills and fees"/><Metric name="NAV" value={money(p.nav)} note="Cash + current marked positions"/><Metric name="REALIZED P&L" value={money(p.realized_pnl)} note="Closed positions"/><Metric name="UNREALIZED P&L" value={money(p.unrealized_pnl)} note="Current marks vs cost basis"/></section></article><article className="panel"><Title eyebrow="EXPOSURE" title="Risk footprint" badge="FACT"/><Row name="Gross exposure" value={money(p.gross_exposure)}/><Row name="Net exposure" value={money(p.net_exposure)}/><Row name="Current drawdown" value={percent(p.drawdown)}/></article><article className="panel"><Title eyebrow="POSITIONS" title="Current holdings" badge={Object.keys(p.positions).length?"FACT":"NOT AVAILABLE"}/>{Object.keys(p.positions).length?Object.entries(p.positions).map(([symbol,qty])=><div className="position" key={symbol}><strong>{symbol} · LONG</strong><span>{qty} shares · avg {money(p.average_prices[symbol as keyof typeof p.average_prices])}</span><b>{money(Number(qty)*Number(p.last_prices[symbol as keyof typeof p.last_prices]))}</b><small>Last {money(p.last_prices[symbol as keyof typeof p.last_prices])} · unrealized {money(p.unrealized_pnl)}</small></div>):<p>No position at this replay point.</p>}</article><article className="panel span2"><Title eyebrow="LEDGER" title={`${snap.ledger.length} visible records`} badge="APPEND ONLY"/><div className="dataList">{snap.ledger.slice(-10).map(e=><Row key={e.entry_id} name={`${e.sequence} · ${e.entry_type}`} value={e.description||e.amount}/>)}</div></article><Equity snap={snap}/></section>}
function System({snap,status}:{snap:Snapshot,status:string}){return <section className="viewGrid"><article className="panel"><Title eyebrow="REPRODUCIBILITY" title="Run identity" badge="FACT"/><Row name="run_id" value={snap.run.run_id}/><Row name="dataset_id" value={snap.run.dataset_id}/><Row name="random_seed" value={snap.run.random_seed}/><Row name="ReplayClock" value={status}/><Row name="event index / count" value={`${snap.replay.event_index+1} / ${snap.replay.event_count}`}/><Row name="ledger count" value={snap.run.ledger_entry_count}/></article><article className="panel"><Title eyebrow="INTEGRITY" title="Hashes & code" badge="FACT"/><div className="hashBlock"><label>CONFIG HASH</label><code>{snap.run.config_hash}</code><label>RESULT HASH</label><code>{snap.run.result_hash}</code><label>CODE COMMIT</label><code>{snap.run.code_commit}</code></div></article><article className="panel span2"><Title eyebrow="CONFIG SNAPSHOT" title="Parameters used by this run" badge="FACT"/><div className="configGrid">{Object.entries(snap.config_snapshot).map(([k,v])=><Row key={k} name={k} value={String(v)}/>)}</div></article></section>}
function Decision({snap,advanced,setAdvanced,close}:any){const d=snap.decisions.at(-1);if(!d)return <div className="modalBackdrop"><section className="decisionModal"><header><h1>No completed decision at this replay point</h1><button onClick={close}>CLOSE ×</button></header><p>Advance replay until a Fill and its ledger records exist.</p></section></div>;const a=d.advanced;return <div className="modalBackdrop"><section className="decisionModal" role="dialog" aria-modal="true"><header><div><span className="eyebrow">DECISION TRACE · {a.intent.timestamp}</span><h1>{a.intent.symbol} · {a.intent.side.toUpperCase()}</h1></div><button onClick={close}>CLOSE ×</button></header><div className="modeToggle"><button className={!advanced?"selected":""} onClick={()=>setAdvanced(false)}>SIMPLE</button><button className={advanced?"selected":""} onClick={()=>setAdvanced(true)}>ADVANCED</button></div>{!advanced?<div className="simpleTrace">{Object.entries(d.simple).map(([k,v],i)=><Trace key={k} n={String(i+1).padStart(2,"0")} title={label(k)} body={v}/>)}</div>:<div className="advancedTrace"><TraceSection title="MARKET EVENT"><Row name="timestamp" value={a.market_event.timestamp}/><Row name="OHLCV" value={`${a.market_event.data.open} / ${a.market_event.data.high} / ${a.market_event.data.low} / ${a.market_event.data.close} / ${a.market_event.data.volume}`}/></TraceSection><TraceSection title="FEATURES">{Object.entries(a.features).map(([k,v])=><Row key={k} name={k} value={v??"NOT AVAILABLE"}/>)}</TraceSection><TraceSection title="INTENT / RISK"><Row name="signal score" value={a.intent.signal_score}/><Row name="reason codes" value={a.intent.reason_codes.join(", ")}/><Row name="requested / approved" value={`${a.portfolio_request.requested_qty} / ${a.risk_assessment.approved_qty}`}/><Row name="risk decision" value={a.risk_assessment.decision}/></TraceSection><TraceSection title="ORDER / EXECUTION / FILL"><Row name="order" value={`${a.order.order_type} · ${a.order.status}`}/><Row name="execution" value={`${a.execution.outcome} · ${a.execution.reason}`}/><Row name="fill" value={`${a.fill.qty} @ ${a.fill.price}`}/><Row name="fee" value={a.fill.fee}/></TraceSection><TraceSection title="LEDGER / P&L"><Row name="transaction P&L" value={a.pnl}/><pre>{a.ledger_entries.map((e:any)=>`${e.sequence} · ${e.entry_type} · ${e.amount}`).join("\n")}</pre></TraceSection></div>}</section></div>}
function Metrics({snap}:{snap:Snapshot}){return <article className="panel metricsPanel"><Title eyebrow="RUN METRICS" title="Performance & evidence" badge="LEDGER BASED"/><div className="metricsRows">{Object.entries(snap.metrics).map(([k,m])=><Row key={k} name={k} value={m.value==null?label(m.status):k.includes("return")||k.includes("drawdown")||k==="turnover"?percent(m.value):String(m.value)}/>)}</div></article>}
function Equity({snap}:{snap:Snapshot}){const c=snap.equity_curve,values=c.map(p=>Number(p.nav)),min=Math.min(...values,100000),max=Math.max(...values,100000),range=Math.max(1,max-min);return <article className="panel equityPanel"><Title eyebrow="LIVE NAV / EQUITY CURVE" title="Point-in-time NAV history" badge="NO FUTURE NAV"/><div className="equityBars">{values.map((v,i)=><i key={i} style={{height:`${12+((v-min)/range)*88}%`}} title={money(v)}/>)}</div><div className="equityLegend"><span>Cash {money(snap.portfolio.cash)}</span><span>NAV {money(snap.portfolio.nav)}</span><span>Drawdown {percent(snap.portfolio.drawdown)}</span></div></article>}
function PriceChart({events}:{events:any[]}){return <div className="priceChart">{events.map(e=><i key={e.event_id} style={{height:`${Math.max(4,20+(Number(e.data.close)-Number(events[0].data.close))*6)}px`}} title={`${e.timestamp}: ${e.data.close}`}/>)}</div>}
function Pipeline({snap}:{snap:Snapshot}){const hasFeature=Boolean(snap.market.features),hasDecision=snap.decisions.length>0,hasOrder=snap.ledger.some(e=>e.entry_type==="order"),hasFill=snap.ledger.some(e=>e.entry_type==="fill");return <section className="pipeline" aria-label="Current decision pipeline">{[["MARKET",true],["FEATURE",hasFeature],["STRATEGY",hasFeature],["INTENT",hasDecision],["RISK",hasDecision],["ORDER",hasOrder],["FILL",hasFill]].map(([name,done],i)=><span key={String(name)} className={done?"done":"waiting"}>{name} {done?"✓":"—"}{i<6&&<b>→</b>}</span>)}</section>}
function EventStream({snap}:{snap:Snapshot}){const e=snap.market.event,d=snap.decisions.at(-1),current=snap.ledger.filter(x=>x.timestamp.slice(0,10)===e.timestamp.slice(0,10)).slice(-10);return <article className="panel eventStream"><Title eyebrow="EVENT STREAM" title="What the runtime just did" badge="RUNTIME ONLY"/><div className="feed"><p><time>{e.timestamp.slice(0,16).replace("T"," ")}</time><b>MARKET</b>{e.data.symbol} close {e.data.close}</p>{snap.market.features&&<p><time>{e.timestamp.slice(0,16).replace("T"," ")}</time><b>FEATURE</b>Snapshot updated for {e.data.symbol}</p>}{d&&<><p className="important"><time>{d.advanced.intent.timestamp.slice(0,16).replace("T"," ")}</time><b>INTENT</b>{d.advanced.intent.side.toUpperCase()} {d.advanced.intent.symbol}</p><p className="important"><time>{d.advanced.intent.timestamp.slice(0,16).replace("T"," ")}</time><b>RISK</b>{d.advanced.risk_assessment.decision.toUpperCase()}</p></>}{current.map(x=><p key={x.entry_id} className={x.entry_type==="fill"?"important":""}><time>{x.timestamp.slice(0,16).replace("T"," ")}</time><b>{x.entry_type.toUpperCase()}</b>{x.symbol||x.description||x.amount}</p>)}</div></article>}
function Evidence({value="FACT"}:{value?:string}){return <em className={`evidence ${value.toLowerCase().replaceAll(" ","-")}`}>{value}</em>}
function Metric({name,value,note}:{name:string,value:string,note:string}){return <article className="metric"><label>{name}</label><b>{value}</b><small>{note}</small><Evidence value={value.includes("DATA")||value.includes("AVAILABLE")?value:"FACT"}/></article>}
function Title({eyebrow,title,badge}:{eyebrow:string,title:string,badge:string}){return <div className="panelHead"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><span className="normalPill">{badge}</span></div>}
function Row({name,value}:{name:string,value:unknown}){return <div className="dataRow"><span>{label(name)}</span><strong>{String(value)}</strong></div>}
function Trace({n,title,body}:{n:string,title:string,body:unknown}){return <article><span>{n}</span><div><label>{title}</label><p>{String(body)}</p></div></article>}
function TraceSection({title,children}:{title:string,children:React.ReactNode}){return <section><h3>{title}</h3>{children}</section>}
